name: Datadog CI
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: datadog/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_INSIDE_CI: "true"
          DD_HOSTNAME: "none"

    steps:
      - name: my-python-app
        env:
          DD_ENV: "ci" 
          DD_SERVICE: "my-python-app"
        run: |
          pip install -U ddtrace
          pip install pytest
          pytest --ddtrace
