name: DatadogCI
on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: datadog/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
    
    steps:
      - uses: actions/checkout@v2
      - name: my-python-app
        run: |
          pip install -U ddtrace
          pip install pytest
          pytest --ddtrace
