
name: report

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            var pullRequest = await github.pulls.list({
              title: "New PR",
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'master',
              base: 'testing'
            });
            console.log(pullRequest);
