
name: report

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            var existingPr = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'master',
              base: 'testing'
            });
            console.log(existingPr);
            var prData = existingPr.data[0];
            console.log(prData);
            if (prData.title === "New PR") {
                console.log("PR already present");
            }
            else {
                try {
                    github.pulls.create({
                        title: "New PR",
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        head: 'master',
                        base: 'testing'
                    });
                } catch (error) {
                    console.log(error);
                }
            }
