
name: report

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            var existingPr = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'master',
              base: 'testing'
            });
            var prData = existingPr.data[0]
            if (prData.title === "Master -> Testing") {
                console.log("PR already present");
            }
            else {
                github.pulls.create({
                    title: "Master -> Testing",
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    head: 'master',
                    base: 'testing'
                })
            }

