
name: report

on: pull_request

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Adding Comment
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.actor }}"
          echo "Hello world!" > report.md
          cml-send-comment report.md

      - name: Extract branch name
        if: github.event_name != 'pull_request'
        run: |
          echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}"

      - name: Extract branch name on PR
        if: github.event_name == 'pull_request'
        run: |
          echo "GIT_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_HEAD_REF}"

      - name: Send Slack notification (#qa-dev-handshake)
        run: |
          curl -s -X POST --data "payload={\"text\": \"Testing branch has been deployed by ${{ github.actor }}\"}"
