
name: report

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.pulls.create({
              title: "New PR",
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'master',
              base: 'testing'
            })
