
name: report

on:
  pull_request:
    branches:
      - 'master'
      - 'testing'
      - 'staging'
      - 'release'
  push:
    branches:
      - 'testing'
      - 'staging'

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v4
        name: 'Raise PRs'
        with:
          script: |
            const script = require('./.github/workflows/pullRequestAction.js')
            await script({github, context, core})

      - name: my-python-app
        env:
          DD_ENV: "ci" 
          DD_SERVICE: "my-python-app"
        run: |
          pip install -U ddtrace
          pip install pytest
          pytest --ddtrace
