
name: report

on: [push, pull_request]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Adding Comment
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Hello world!" > report.md
          cml-send-comment report.md
